#ifndef UIEVENTCODES
#define UIEVENTCODES

// handled by NoiseWindow
#define UIEVT_CONTENTSCHANGED 1

// handled by MapFrame
#define UIEVT_BTCLICKEDNOISE0 2
#define UIEVT_BTCLICKEDNOISE1 3
#define UIEVT_BTCLICKEDNOISE2 4

#define UIEVT_BTCLICKEDMAP0 5
#define UIEVT_BTCLICKEDMAP1 6
#define UIEVT_BTCLICKEDMAP2 7

#endif